cache: bundler
language: ruby
rvm: 2.2.0
sudo: false

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - rake db:create:all
  - rake db:migrate
  - rake db:test:prepare

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

script: RAILS_ENV=test bundle exec rspec spec
