os: linux
version: 0.0

files:
  - source: /
    destination: /var/www/blog/codedeploy
    overwrite: yes

hooks:
  BeforeInstall:
    - location: script/codedeploy/clean.sh
      runas: root

  AfterInstall:
    - location: script/codedeploy/permission.sh
      runas: root

    - location: script/codedeploy/envs.sh
      runas: deploy

    - location: script/codedeploy/bundle.sh
      runas: deploy

    - location: script/codedeploy/migrate.sh
      runas: deploy

    - location: script/codedeploy/precompile.sh
      runas: deploy

    - location: script/codedeploy/symlink.sh
      runas: deploy

    - location: script/codedeploy/whenever.sh
      runas: deploy

  ApplicationStart:
    - location: script/codedeploy/unicorn_restart.sh
      runas: root

    - location: script/codedeploy/nginx_restart.sh
      runas: root
