version: '3.8'

services:
  app:
    build: .
    command: bundle exec rails s -b 0.0.0.0

    environment:
      DATABASE_HOST: database

    ports:
      - 3000:3000

    depends_on:
      - database

    volumes:
      - ./:/app

  database:
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: trust

    image: mysql:latest

    ports:
      - 3306:3306
