defaults: &defaults
  aws_access_key_id: "<%= ENV['AWS_ACCESS_KEY_ID'] %>"
  aws_secret_access_key: "<%= ENV['AWS_SECRET_ACCESS_KEY'] %>"
  existing_remote_files: 'delete'
  fog_directory: 'blogy'
  fog_provider: 'AWS'
  fog_region: 'sa-east-1'
  gzip_compression: true

development:
  <<: *defaults
  enabled: false

production:
  <<: *defaults

test:
  <<: *defaults
  enabled: false
