analytics:   'UA-19499234-1'
author:      'Washington Botelho'
description: 'Artigos sobre Ruby, Rails, Java, VRaptor, Python, jQuery, JavaScript, CSS e muito mais.'
email:       'wbotelhos@gmail.com'
github:      'http://github.com/wbotelhos'
keywords:    'ruby,rails,java,python,jquery,javascript'
labs:        'capty,chrony,flapy,flury,gridy,mory,populaty,raty,stepy,styly,taby,treefy,validaty'
linkedin:    'http://linkedin.com/in/wbotelhos'
quote:       'Se você não tem dom, tenha vontade!'
twitter:     'http://twitter.com/wbotelhos'
url:         'wbotelhos.com'
url_http:    'http://wbotelhos.com'
url_www:     'www.wbotelhos.com'
