author:       'Washington Botelho'
description:  'Se você não tem dom, tenha vontade!'
email:        'wbotelhos@gmail.com'
github:       'wbotelhos'
linkedin:     'wbotelhos'
nick:         'wbotelhos'
url:          'wbotelhos.com'
url_http:     'http://wbotelhos.com'
url_www:      'www.wbotelhos.com'
year:         '2013'
