author:      'Washington Botelho'
description: 'Artigos sobre Ruby, Rails, Java, VRaptor, Python, jQuery, JavaScript, CSS e muito mais.'
email:       'wbotelhos@gmail.com'
github:      'wbotelhos'
keywords:    'ruby,rails,java,python,jquery,javascript'
labs:        'capty,chrony,flapy,flury,gridy,mory,populaty,raty,stepy,styly,taby,treefy,validaty'
linkedin:    'wbotelhos'
quote:       'Se você não tem dom, tenha vontade!'
twitter:     'wbotelhos'
url:         'wbotelhos.com'
url_http:    'http://wbotelhos.com'
url_www:     'www.wbotelhos.com'
