author:      'Washington Botelho'
description: 'Ruby, Rails, Python, Java, JavaScript, jQuery e muito mais.'
email:       'wbotelhos@gmail.com'
github:      'wbotelhos'
keywords:    'ruby,rails,java,python,jquery,javascript'
linkedin:    'wbotelhos'
quote:       'Se você não tem dom, tenha vontade!'
twitter:     'wbotelhos'
url:         'wbotelhos.com'
url_http:    'http://wbotelhos.com'
url_www:     'www.wbotelhos.com'
