default: &default
  adapter: mysql2
  encoding: utf8
  host: localhost
  password: root
  pool: 5
  reconnect: false
  username: root

development:
  <<: *default
  database: wbotelhos_development

production:
  <<: *default
  database: wbotelhos_production

test:
  <<: *default
  database: wbotelhos_test
