default: &default
  adapter: mysql2
  encoding: utf8
  host: localhost
  password:
  pool: 5
  reconnect: false
  username: root

development:
  <<: *default
  database: blogy_development

production:
  <<: *default
  database: blogy_production

test:
  <<: *default
  database: blogy_test
