development:
  adapter: mysql2
  database: blogy_development
  encoding: utf8
  host: 127.0.0.1
  username: root

production:
  adapter: mysql2
  database: <%= ENV["DATABASE_DATABASE"] %>
  encoding: utf8
  host: <%= ENV["DATABASE_HOST"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["DATABASE_USERNAME"] %>

test:
  adapter: mysql2
  database: blogy_test
  encoding: utf8
  host: 127.0.0.1
  username: root
